[package]
name = "iapyx"
version = "0.0.1"
authors = ["dkijania <dariusz.kijania@iohk.io>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bech32 = "0.8"
wallet-core = { git = "https://github.com/input-output-hk/chain-wallet-libs.git", branch = "master"}
wallet = { git = "https://github.com/input-output-hk/chain-wallet-libs.git", branch = "master"}
hdkeygen = { git = "https://github.com/input-output-hk/chain-wallet-libs.git", branch = "master"}
chain-crypto = { git = "https://github.com/input-output-hk/chain-libs.git", branch = "master" }
chain-core = { git = "https://github.com/input-output-hk/chain-libs.git", branch = "master"  }
chain-addr = { git = "https://github.com/input-output-hk/chain-libs.git", branch = "master" }
chain-ser = { git = "https://github.com/input-output-hk/chain-libs.git", branch = "master"  }
chain-impl-mockchain = { git = "https://github.com/input-output-hk/chain-libs.git", branch = "master"  }
chain-time = { git = "https://github.com/input-output-hk/chain-libs.git", branch = "master" }
chain-vote = { git = "https://github.com/input-output-hk/chain-libs.git", branch = "master" }
hex = "0.4"
rand = "0.8"
dirs = "4.0"
rand_core = "0.6"
itertools = "0.9.0"
cryptoxide = "0.3.2"
ed25519-bip32 = "^0.3.1"
jcli = { git = "https://github.com/input-output-hk/jormungandr.git", branch = "master" }
jormungandr-lib = { git = "https://github.com/input-output-hk/jormungandr.git", branch = "master" }
jormungandr-automation = { git = "https://github.com/input-output-hk/jormungandr.git", branch = "master" }
thor = { git = "https://github.com/input-output-hk/jormungandr.git", branch = "master" }
hersir = { git = "https://github.com/input-output-hk/jormungandr.git", branch = "master" }
jortestkit = { git = "https://github.com/input-output-hk/jortestkit.git", branch = "master" }
catalyst-toolbox = { git = "https://github.com/input-output-hk/catalyst-toolbox.git", branch = "swtich_stake_from_funds_to_token", features=["test-api"]}
valgrind = { path = "../valgrind"}
hyper = "0.13.6"
thiserror = "1.0"
serde_json = "1.0.53"
serde_yaml = "0.8.23"
serde = { version = "1.0", features = ["derive"] }
chrono = { version = "0.4", features = ["serde"] }
regex = "*"
dialoguer = "0.9"
structopt = "0.3"
console = "0.15"
csv = "1.1"
warp = { version = "0.3", features = ["tls"] }
warp-reverse-proxy = "0.3.2"
tokio = { version = "^1.4.0", features = ["macros", "signal", "rt", "fs", "sync"] }
url = "2.1.1"
image = "0.23.12"
eccoxide = { git = "https://github.com/eugene-babichenko/eccoxide.git", branch = "fast-u64-scalar-mul", features = ["fast-u64-scalar-mul"], optional = true }
rayon = "1"
bincode = "1.3.3"
cocoon =  { git = "https://github.com/dkijania/cocoon.git" }

[dependencies.reqwest]
version = "0.10.6"
default-features = false
features = ["blocking","rustls-tls"]
