[package]
name = "iapyx"
version = "0.0.1"
authors = ["dkijania <dariusz.kijania@iohk.io>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bech32 = "0.7"
wallet-core = { git = "https://github.com/input-output-hk/chain-wallet-libs.git", branch = "master" }
wallet = { git = "https://github.com/input-output-hk/chain-wallet-libs.git", branch = "master" }
hdkeygen = { git = "https://github.com/input-output-hk/chain-wallet-libs.git", branch = "master" }
bip39 = { git = "https://github.com/input-output-hk/chain-wallet-libs.git", branch = "master" }
chain-crypto = { git = "https://github.com/input-output-hk/chain-libs.git", branch = "master" }
chain-core = { git = "https://github.com/input-output-hk/chain-libs.git", branch = "master" }
chain-addr = { git = "https://github.com/input-output-hk/chain-libs.git", branch = "master" }
chain-ser = { git = "https://github.com/input-output-hk/chain-libs.git", branch = "master" }
chain-impl-mockchain = { git = "https://github.com/input-output-hk/chain-libs.git", branch = "master" }
hex = "0.4"
rand = "0.8"
indicatif = "0.15"
rand_core = "0.6"
cryptoxide = "0.3.2"
ed25519-bip32 = "^0.3.1"
jormungandr-testing-utils ={ git = "https://github.com/input-output-hk/jormungandr.git", rev = "26f6fc15911863b5f3cf047d6d1789cd0cc39ba0" }
jormungandr-lib = { git = "https://github.com/input-output-hk/jormungandr.git", rev = "26f6fc15911863b5f3cf047d6d1789cd0cc39ba0" }
jortestkit = { git = "https://github.com/input-output-hk/jortestkit.git", branch="master" }
signals-handler = { path = "../signals-handler" }
hyper = "0.13.6"
futures = "0.3.8"
thiserror = "1.0"
serde_json = "1.0.53"
serde = { version = "1.0", features = ["derive"] }
chrono = { version = "0.4", features = ["serde"] }
regex = "*"
dialoguer = "0.6.2"
structopt = "0.3"
console = "0.11"
warp = { version = "0.3", features = ["tls"] }
warp-reverse-proxy = "0.3.2"
tokio = { version = "^1.4.0", features = ["macros", "signal", "rt", "fs", "sync","process"] }
url = "2.1.1"
image = "0.23.12"
eccoxide = { git = "https://github.com/eugene-babichenko/eccoxide.git", branch = "fast-u64-scalar-mul", features = ["fast-u64-scalar-mul"], optional = true }

[dependencies.reqwest]
version = "0.10.6"
default-features = false
features = ["blocking","rustls-tls"]
