version: 2.1

executors:
  rust-stable:
    docker:
      - image: cimg/rust:1.53.0-node
    working_directory: /home/circleci/build
    resource_class: xlarge

jobs:
  cargo_fetch:
    docker:
      - image: cimg/rust:1.53.0-node
    steps:
      - checkout
      - run: git --version
      - run:
          name: Get top commit hash of cargo registry index
          command: |
            git ls-remote --heads https://github.com/rust-lang/crates.io-index.git master |
              cut -f 1 | tee .circleci/crates.io-index.head
      - restore_cache:
          name: Restore cargo registry index from cache
          keys:
            - cargo-index-v2-{{ checksum ".circleci/crates.io-index.head" }}
            - cargo-index-v2-
      - restore_cache:
          name: Restore dependency crates from cache
          keys:
            - cargo-deps-v3-{{ checksum "Cargo.lock" }}
      - run:
          name: Fetch dependencies and update cargo registry index
          command: |
            cargo fetch
            git -C /home/circleci/.cargo/registry/index/github.com-1ecc6299db9ec823 \
                show-ref -s refs/remotes/origin/master |
              tee .circleci/crates.io-index.head
      - save_cache:
          name: Save cargo registry index into cache
          key: cargo-index-v2-{{ checksum ".circleci/crates.io-index.head" }}
          paths:
            - /home/circleci/.cargo/registry/index
      - save_cache:
          name: Save dependency crates into cache
          key: cargo-deps-v3-{{ checksum "Cargo.lock" }}
          paths:
            /home/circleci/.cargo/registry/cache
            /home/circleci/.cargo/git/db
      - persist_to_workspace:
          root: .
          paths:
            - .circleci/crates.io-index.head

  test_debug:
    executor: rust-stable
    environment:
      RUSTFLAGS: -D warnings
      CARGO_INCREMENTAL: 0
    steps:
      - test

commands:
  test:
    description: "Steps for the test jobs"
    parameters:
      mode:
        type: string
        default: ''
      cargo_behavior:
        type: string
        default: --verbose
    steps:
      - checkout
      - attach_workspace:
          at: .
      - restore_cache:
          name: Restore cargo registry index from cache
          keys:
            - cargo-index-v2-{{ checksum ".circleci/crates.io-index.head" }}
      - restore_cache:
          name: Restore dependency crates from cache
          keys:
            - cargo-deps-v3-{{ checksum "Cargo.lock" }}
      - run:
          name: install build reqs
          command: |
            sudo apt update && sudo apt upgrade -y
            sudo apt install build-essential libssl-dev pkg-config    
      - run:
          name: Print version information
          command: rustc --version; cargo --version
      - run:
          name: checkout jormungandr
          command: |
            git clone https://github.com/input-output-hk/jormungandr.git
            cd jormungandr
            git checkout 92dfe2c6fed63acbad0753b7f3736268b95713f6
      - run:
          name: install jormungandr
          command: |
            cd jormungandr
            cargo install --path jormungandr --locked
            cargo install --path jcli --locked
      - run:
          name: checkout vit-station-service
          command: |
            git clone https://github.com/input-output-hk/vit-servicing-station.git
            cd vit-servicing-station
            git checkout 75a3c30211892c32a0edf1ff6b4b368d5e3a0e82
      - run:
          name: install vit-station-service
          command: |
            cd vit-servicing-station
            cargo install --path vit-servicing-station-server --locked
      - run:
          name: install iapyx utils
          command: |
            cargo install --path iapyx --locked
      - run:
          name: Run tests
          no_output_timeout: 60m
          environment:
            RUST_BACKTRACE: 1
          command: |
            cargo test --release -- --test-threads=1

workflows:
  version: 2
  test_all:
    jobs:
      - cargo_fetch
      - test_debug:
          requires:
            - cargo_fetch
