name: Setup Nix Environment
inputs:
  CACHIX_AUTH_TOKEN:
    required: true
    description: 'Cachix Auth Token'
runs:
  using: "composite"
  steps:

    - name: Installing Nix
      uses: cachix/install-nix-action@v16
      with:
        nix_path: nixpkgs=channel:nixpkgs-unstable

    - uses: cachix/cachix-action@v10
      with:
        name: iog
        authToken: '${{ inputs.CACHIX_AUTH_TOKEN }}'

    - name: Direnv setup
      run: |
        eval "$(nix run nixpkgs#direnv -- hook bash)"
        nix run nixpkgs#direnv -- allow
        nix run nixpkgs#direnv -- export gha >> "$GITHUB_ENV"

