name: Setup Nix Environment
inputs:
  CACHIX_AUTH_TOKEN:
    required: true
    description: 'Cachix Auth Token'
runs:
  using: "composite"
  steps:

    - name: Installing Nix
      uses: cachix/install-nix-action@v16
      with:
        nix_path: nixpkgs=channel:nixpkgs-unstable
        extra_nix_config: |
          keep-derivations = true
          keep-outputs = true

    - uses: cachix/cachix-action@v10
      with:
        name: iog
        authToken: '${{ inputs.CACHIX_AUTH_TOKEN }}'

    - name: Direnv setup
      shell: bash
      run: |
        nix profile install nixpkgs#direnv
        nix profile install nixpkgs#nix-direnv

        eval "$(direnv hook bash)"
        source $HOME/.nix-profile/share/nix-direnv/direnvrc

        direnv allow
        direnv export gha >> "$GITHUB_ENV"

