[package]
name = "vitup"
version = "0.0.1"
authors = ["dkijania <dariusz.kijania@iohk.io>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
custom_debug = "0.5"
dialoguer = "0.10.0"
assert_fs = "1.0"
glob = "0.3.0"
ctrlc = "3.2.1"
walkdir = "2.3.1"
csv = "1.1"
itertools = "0.10.3"
chain-core           = { git = "https://github.com/input-output-hk/chain-libs.git", branch = "master" }
chain-crypto         = { git = "https://github.com/input-output-hk/chain-libs.git", branch = "master", features = [ "property-test-api" ] }
chain-addr           = { git = "https://github.com/input-output-hk/chain-libs.git", branch = "master", features = [ "property-test-api" ] }
chain-impl-mockchain = { git = "https://github.com/input-output-hk/chain-libs.git", branch = "master", features = [ "property-test-api" ] }
chain-time           = { git = "https://github.com/input-output-hk/chain-libs.git", branch = "master" }
chain-vote           = { git = "https://github.com/input-output-hk/chain-libs.git", branch = "master" }
proptest = { git = "https://github.com/input-output-hk/proptest.git" }
jormungandr-lib = { git = "https://github.com/input-output-hk/jormungandr.git", branch = "master" }
jormungandr-automation = { git = "https://github.com/input-output-hk/jormungandr.git", branch = "master" }
thor = { git = "https://github.com/input-output-hk/jormungandr.git", branch = "master" }
hersir = { git = "https://github.com/input-output-hk/jormungandr.git", branch = "master" }
jortestkit = { git = "https://github.com/input-output-hk/jortestkit.git", branch = "master" }
vit-servicing-station-tests = { git = "https://github.com/input-output-hk/vit-servicing-station.git", branch = "master" }
vit-servicing-station-lib = { git = "https://github.com/input-output-hk/vit-servicing-station.git", branch = "master" }
catalyst-toolbox = { git = "https://github.com/input-output-hk/catalyst-toolbox.git", branch = "main"}
snapshot-lib = { git = "https://github.com/input-output-hk/catalyst-toolbox.git", branch = "main" }
valgrind = { path = "../valgrind" }
poldercast = { git = "https://github.com/primetype/poldercast.git", rev = "8305f1560392a9d26673ca996e7646c8834533ef" }
rand = "0.8"
path-slash = "0.2.0"
netstat2 = "0.9"
time = { version = "0.3.7", features=["serde","serde-well-known","parsing"]} 
fake = { version = "2.2", features=['chrono','http']}
strum = "0.21.0"
strum_macros = "0.25.2"
rand_core = "0.6"
rand_chacha = "0.3"
tempdir = "0.3.7"
function_name = "0.2.0"
diffy = "0.2.1"
regex = "1.4"
structopt = "0.3"
thiserror = "1.0"
warp-reverse-proxy = "0.3.2"
hex = "0.4"
futures = "0.3.8"
console = "0.15"
indicatif = "0.15"
lazy_static = "1"
serde_json = "1.0"
serde_yaml = "0.8"
yaml-rust = "0.4.4"
serde = { version = "1", features = ["derive"] }
warp = "0.3"
tokio = { version = "1.4", features = ["macros","rt","rt-multi-thread"] }
json = "0.12.4"
image = "0.23.12"
base64 = "0.12.1"
uuid = { version = "0.8", features = ["serde", "v4"] }
tracing-subscriber = "0.2.16"
tracing = "0.1"
tracing-appender = "0.1.2"
hyper = { version = "0.14.17", features = ["server"] }
rustls = "0.20.4"
rustls-pemfile = "0.2.1"
tokio-rustls = "0.23.2"
tokio-stream = { version = "0.1.8", features = ["net"] }

[dev-dependencies]
quickcheck = "0.9"
quickcheck_macros = "0.9"
assert_fs ="1.0"
assert_cmd = "1.0"

[dependencies.reqwest]
version = "0.10.10"
default-features = false
features = ["blocking", "rustls-tls", "json"]

[dev-dependencies.reqwest]
version = "0.10.10"
default-features = false
features = ["blocking", "rustls-tls","native-tls", "json"]
