{
	"port": 8080,
    "jcli": "jcli.exe",
    "result-dir":"c:\\Work\\iok\\registration\\test",
    "cardano-cli":"c:\\Work\\iohk\\cardano-cli\\cardano-cli",
    "voter-registration":"voter-registration.exe",
    "catalyst-toolbox":"catalyst-toolbox.exe",
    "network": {
        "testnet": 10907416
    }
}