[package]
name = "snapshot-trigger-service"
version = "0.1.0"
authors = ["dkijania <dariusz.kijania@iohk.io>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
uuid = { version = "0.8", features = ["serde","v4"] }
chrono = "0.4"
walkdir = "2.3.1"
structopt = "0.3"
jortestkit = { git = "https://github.com/input-output-hk/jortestkit.git", branch= "master" }
jormungandr-lib = { git = "https://github.com/input-output-hk/jormungandr.git", branch = "update-chain-libs" }
chain-addr = { git = "https://github.com/input-output-hk/chain-libs.git", branch = "remove-deserialize-trait" }
futures = "0.3.8"
assert_fs = "1.0"
serde = { version = "1", features = ["derive"] }
warp = "0.3"
thiserror = "1.0"
tokio = { version = "1.2", features = ["macros","rt","process"] }
serde_json = "1.0"
serde_yaml = "0.8"
signals-handler = { path = "../signals-handler" }

[dependencies.reqwest]
version = "0.10.10"
default-features = false
features = ["blocking", "rustls-tls","json"]
